config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    
    get "/", to: "pages#home", as: "root"

    get '/blogs', to: 'blogs#index', as: 'blogs'
    post '/blogs', to: 'blogs#create', as: "create_blog"
    get '/blogs/new', to: 'blogs#new', as: 'new_blog'
    get '/blogs/:id', to: 'blogs#show', as: 'blog'
    put '/blogs/:id', to: 'blogs#update'
    patch '/blogs/:id', to: 'blogs#update'
    delete '/blogs/:id', to: 'blogs#destroy', as: 'destroy_blog'
    get '/blogs/:id/edit', to: 'blogs#edit', as: 'edit_blog'
    
    post '/notes', to: 'notes#create', as: 'create_note'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :notes, dependent: :destroy
    validates :title, presence: true
    has_one_attached :picture
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs, dependent: :destroy
  has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  before_action :set_blog, only: [:show]
  before_action :set_user_blog, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  

  def index
    @blog = Blog.all.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end
  
  def create
    @blog = current_user.blogs.create(blog_params)
    
    if @blog.errors.any?
      render "new"
    else
      redirect_to blogs_path
    end
  end
  
  def show
    @notes = Note.all
  end
  
  def update
    @blog = Blog.update(params[:id], blog_params)
    
    if @blog.update(blog_params)
     flash[:notice] = "Blog was updated"
     redirect_to blogs_path
    else
     flash[:notice] = "Blog was not updated"
     render 'edit'
    end
  end
  
  def edit
  
  end

  def destroy
    Blog.find_by_id(params[:id]).destroy
    flash[:notice] = "Blog post was deleted"
    redirect_to blogs_path
  end
  
  
  private
    
  def blog_params
     params.require(:blog).permit(:title, :description, :picture)
    end
  
  def set_blog
     @blog = Blog.find(params[:id])
  end

  def set_user_blog
    @blog = current_user.blogs.find_by_id(params[:id])
    if @blog == nil
      redirect_to blogs_path
    end
  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

    def create
        
        Note.create(user_id: current_user.id, blog_id: params[:blog_id], text_field: params[:text_field])
        redirect_to blog_path(params[:blog_id])
        
    end

    # def destroy
    #   @blog = Blog.find(params[:blog_id])
    #   @blog = @blog.notes.find(params[:id])
    #   @note.destroy
    #   redirect_to blog_path(@blog)
    # end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!
    
    def home
    
    end

end

app/controllers/posts_controller.rb
class PostController < ApplicationController
    before_action :authenticate_user!
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<% if blog.errors.any? %>
    <ul>
        <% blog.errors.full_messages.each do |error|%>
            <li> <%= error %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for blog do |f| %>
 <div class = "form-div">
  <%= f.label :title %><br>
  <%= f.text_field :title, value: blog.title %>
 </div>
 <div class = "form-div">
  <%= f.label :description %><br>
  <%= f.text_field :description, value: blog.description %>
 </div>
 <div>
  <%= f.label :picture %> 
  <%= f.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
 </div>
 <div class = "form-div">
  <%= f.submit %>
 </div>
<% end %>

app/views/blogs/edit.html.erb
<h1> Edit your blog post here </h1>

<%= render "form", blog: @blog %>

app/views/blogs/index.html.erb
<h1 class = "center">All Blogs</h1>

<div class="blogs">
<% @blog.each do |blog| %>
      <div class="blog">
      <div class="col-md-3">
      <%= image_tag blog.picture if blog.picture.attached? %>
     <span class="heading"><li><%= link_to  "#{blog.title}", blog_path(blog.id) %></li></span>
      <li><%= blog.description %> </li>
    </div>
    </div>

<%end%>

app/views/blogs/new.html.erb
<h1> Start your new blog post here </h1>

<%= render "form", blog: @blog %>

app/views/blogs/show.html.erb
<div class="blog-show">

     <h1> Here are the Blog posts </h1>
     <%= image_tag @blog.picture if @blog.picture.attached? %>
     <li><h2> <%= @blog.title %> </h2></li>
     <li><p> <%= @blog.description %> </p></li>
    <%= form_with model: @blog, local: true, method: "delete" do |form| %>
    <% if current_user.id == @blog.user_id %>
        <%= submit_tag "delete" %>
    <button class= "button2"><%= link_to "edit", edit_blog_path(@blog.id) %> </button>
    <% end %> 
<% end %>
<br>
<br>
<br>

<div>
   


 <%= form_with model: @note, url: create_note_path, local: true, method: "post" do |form| %>

    <%= form.label :"Enter your comment here"%>
    <%= form.text_field :text_field %>
    
    <%= form.hidden_field :blog_id, :value => @blog.id %>
    <%= submit_tag "submit" %>

<% end %>
<h3> Comments </h3>
<% @notes.each do |note| %>
    <% if note.blog_id == @blog.id %>
     <ul class ="comment-list">
        <li> <%= User.find(note.user_id).email %> </li>
    
       <li> <%= note.text_field %> </li>
    </ul>
    <% end %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

       <ul>
        <li> <%= link_to "View All Blogs", blogs_path%><li>
          
          <% if user_signed_in? %>
          <li> <%= link_to "logout", destroy_user_session_path, method: :delete %></li>
          <li> <%= link_to "Create New Blog", new_blog_path %> </li>
          <% else %>
          
          <% end %>
  </ul>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Blog</h1>
<h2> This is the home page  </h2>